#!/usr/bin/env bash

from="../www"
to="./static"

files=(
"fonts/Bitter-Italic.ttf"
"fonts/Bitter-Italic.woff"
"fonts/Bitter-Italic.woff2"
"fonts/Bitter-Regular.ttf"
"fonts/Bitter-Regular.woff"
"fonts/Bitter-Regular.woff2"
"fonts/Bungee-Regular.ttf"
"fonts/Bungee-Regular.woff"
"fonts/Bungee-Regular.woff2"
"fonts/Rubik-Regular.ttf"
"fonts/Rubik-Regular.woff"
"fonts/Rubik-Regular.woff2"
"fonts/subset-Bungee-Regular.ttf"
"fonts/subset-Bungee-Regular.woff"
"fonts/subset-Bungee-Regular.woff2"
"img/awstranscribe.jpg"
"img/awstranscribe.png"
"img/babblenauts.jpg"
"img/babblenauts.png"
"img/caddygen.jpg"
"img/caddygen.png"
"img/couetilcom.jpg"
"img/couetilcom.png"
"img/equinelungexperts.jpg"
"img/equinelungexperts.png"
"img/GitHub-Mark-32px.png"
"img/LI-In-Bug.png"
"img/reactsocialicons.jpg"
"img/reactsocialicons.png"
"img/resume.jpg"
"img/resume.png"
"sat/R20m/output80_nosharp.jpg"
"sat/R20m/output80_nosharp.webp"
"sat/R60m/output80_nosharp.jpg"
"sat/R60m/output80_nosharp.webp"
"sat/R60m/output80_nosharp_1200.jpg"
"sat/R60m/output80_nosharp_1200.webp"
"sat/R60m/output80_nosharp_700.jpg"
"sat/R60m/output80_nosharp_700.webp"
"sat/R60m/output80_nosharp_700_interlace.jpg"
"sat/R60m/output80_nosharp_700_interlace.webp"
"favicon-16x16.png"
"favicon-32x32.png"
"home.css"
"index.css"
"index.js"
"scribble.svg"
)

for file in "${files[@]}"; do
  cp "$from/$file" "$to/${file//\//_}"
done
