version: "3.3"
services:
  caddy-gen:
    container_name: couetil-caddy-gen
    image: "couetilc/caddy-gen:1.0.2"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - caddy-certificates:/data/caddy
      - ../caddy/Caddyfile:/tmp/Caddyfile
      - ../build:/srv/couetil/www
    environment:
      CADDY_SNIPPET: /tmp/Caddyfile

volumes:
  caddy-certificates:
    external: true
    name: caddy-certificates
