name: Build, Test, Deploy

on:
  push:
    branches:
      - master
    tags:
      - prod
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js Version
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1.7.4

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Cache Build
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}

  deploy:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/prod')
    runs-on: macos-latest
    needs: build
    steps:

      - name: Restore Build
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOST }}

      - name: Rsync to Remote
        run: >
          rsync -av
          bootstrap.sh
          secrets.yml
          compose
          build
          caddy
          plausible
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/deployment

      - name: Re-deploy
        run: >
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
          'cd deployment && ./bootstrap.sh'
