name: couetil.com deploy steps

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js Version
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Test
        run: |
          npm run test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Website
        run: |
          aws s3 sync build/ s3://couetil.com/www/

      - name: Invalidate Cloudfront Cache
        run: >
          aws cloudfront create-invalidation
          --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          --paths "/*"

      - name: Purge Cloudflare Cache
        run: >
          curl -X POST "https://api.cloudflare.com/client/v4/zones/023e105f4ecef8ad9ca31a8372d0c353/purge_cache"
          -H "Authorization: Bearer ${{ CLOUDFLARE_API_TOKEN }}
          -H "Content-Type: application/json"
          --data '{"purge_everything":true}'
