name: couetil.com deploy steps

on:
  push:
    branches:
      - master
    tags:
      - prod
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js Version
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Test
        run: |
          npm run test

      - name: Install SSH Key
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/prod')
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOST }}

      - name: Rsync to Remote
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/prod')
        run: >
          rsync -av
          bootstrap.sh
          secrets.yml
          compose
          build
          caddy
          plausible
          ${{ secrets.SSH_USER }}@${{ SSH_HOST }}:~/deployment

      - name: Re-deploy
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/prod')
        run: >
          ssh ${{ secrets.SSH_USER }}@${{ SSH_HOST }}
          'cd deployment && ./bootstrap.sh'
